# Generated by Django 6.0.6 on 2026-06-23 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lifeos_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="duration_estimate",
            field=models.PositiveIntegerField(default=30, help_text="Minutes"),
        ),
        migrations.AddField(
            model_name="task",
            name="is_active",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="task",
            name="started_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="task",
            name="time_spent_seconds",
            field=models.PositiveIntegerField(default=0, help_text="Seconds elapsed"),
        ),
    ]
