# Generated by Django 6.0.6 on 2026-06-27 03:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("lifeos_app", "0002_task_duration_estimate_task_is_active_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExecutionItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                (
                    "item_type",
                    models.CharField(
                        choices=[
                            ("Task", "Task"),
                            ("Subtask", "Subtask"),
                            ("LearningTask", "LearningTask"),
                            ("LifeActivity", "LifeActivity"),
                        ],
                        max_length=50,
                    ),
                ),
                ("is_completed", models.BooleanField(db_index=True, default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("object_id", models.PositiveIntegerField()),
                (
                    "duration_estimate",
                    models.PositiveIntegerField(default=30, help_text="Minutes"),
                ),
                (
                    "time_spent_seconds",
                    models.PositiveIntegerField(default=0, help_text="Seconds elapsed"),
                ),
                ("is_active", models.BooleanField(db_index=True, default=False)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                (
                    "domain_category",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Tech/Career", "Tech/Career"),
                            ("Theater", "Theater"),
                            ("Academy", "Academy"),
                            ("Home", "Home"),
                            ("Governance/Compliance", "Governance/Compliance"),
                        ],
                        db_index=True,
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "para_category",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Projects", "Projects"),
                            ("Areas", "Areas"),
                            ("Resources", "Resources"),
                            ("Archives", "Archives"),
                        ],
                        db_index=True,
                        max_length=100,
                        null=True,
                    ),
                ),
                ("is_archived", models.BooleanField(db_index=True, default=False)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
            ],
        ),
        migrations.CreateModel(
            name="WorkspaceContainer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                (
                    "container_type",
                    models.CharField(
                        choices=[
                            ("Epic", "Epic"),
                            ("Project", "Project"),
                            ("Specialization", "Specialization"),
                            ("Course", "Course"),
                            ("Module", "Module"),
                        ],
                        max_length=50,
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "domain_category",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Tech/Career", "Tech/Career"),
                            ("Theater", "Theater"),
                            ("Academy", "Academy"),
                            ("Home", "Home"),
                            ("Governance/Compliance", "Governance/Compliance"),
                        ],
                        db_index=True,
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "para_category",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Projects", "Projects"),
                            ("Areas", "Areas"),
                            ("Resources", "Resources"),
                            ("Archives", "Archives"),
                        ],
                        db_index=True,
                        max_length=100,
                        null=True,
                    ),
                ),
                ("is_archived", models.BooleanField(db_index=True, default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name="container",
            name="parent",
        ),
        migrations.RemoveIndex(
            model_name="task",
            name="lifeos_app__content_e22fa0_idx",
        ),
        migrations.AddField(
            model_name="executionitem",
            name="content_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="contenttypes.contenttype",
            ),
        ),
        migrations.AddField(
            model_name="workspacecontainer",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="children",
                to="lifeos_app.workspacecontainer",
            ),
        ),
        migrations.DeleteModel(
            name="Container",
        ),
        migrations.RemoveField(
            model_name="task",
            name="content_type",
        ),
        migrations.AddIndex(
            model_name="executionitem",
            index=models.Index(
                fields=["content_type", "object_id"],
                name="lifeos_app__content_ef5b53_idx",
            ),
        ),
        migrations.DeleteModel(
            name="Task",
        ),
    ]
