"""add calendar id

Revision ID: 308ee3649240
Revises: 7b8ffc88faa5
Create Date: 2026-05-31 21:40:12.124399

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '308ee3649240'
down_revision: Union[str, Sequence[str], None] = '7b8ffc88faa5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('google_calendar_id', sqlmodel.sql.sqltypes.AutoString(), server_default=sa.text("''"), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('settings', schema=None) as batch_op:
        batch_op.drop_column('google_calendar_id')

    # ### end Alembic commands ###
