"""add description to Academy work items

Revision ID: 7073b39c2cf5
Revises: 308ee3649240
Create Date: 2026-06-03 21:59:27.763050

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '7073b39c2cf5'
down_revision: Union[str, Sequence[str], None] = '308ee3649240'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), server_default=sa.text("''"), nullable=True))

    with op.batch_alter_table('learningtask', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), server_default=sa.text("''"), nullable=True))

    with op.batch_alter_table('module', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), server_default=sa.text("''"), nullable=True))

    with op.batch_alter_table('specialization', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), server_default=sa.text("''"), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('specialization', schema=None) as batch_op:
        batch_op.drop_column('description')

    with op.batch_alter_table('module', schema=None) as batch_op:
        batch_op.drop_column('description')

    with op.batch_alter_table('learningtask', schema=None) as batch_op:
        batch_op.drop_column('description')

    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.drop_column('description')

    # ### end Alembic commands ###
