"""add Habitat settings

Revision ID: 7b8ffc88faa5
Revises: 0346a4cac67a
Create Date: 2026-05-31 20:46:09.990476

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '7b8ffc88faa5'
down_revision: Union[str, Sequence[str], None] = '0346a4cac67a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('habitat_name', sqlmodel.sql.sqltypes.AutoString(), server_default=sa.text("'Monroe Observatory'"), nullable=False))
        batch_op.add_column(sa.Column('habitat_location', sqlmodel.sql.sqltypes.AutoString(), server_default=sa.text("'Monroe, WA'"), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('settings', schema=None) as batch_op:
        batch_op.drop_column('habitat_location')
        batch_op.drop_column('habitat_name')

    # ### end Alembic commands ###
